//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHENAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Time
    {
        public int id { get; set; }
        public string Text { get; set; }
        public Nullable<System.TimeSpan> Group { get; set; }
    }
}
