//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHENAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Logistics_CO___LTD__Temp_Request
    {
        public byte[] timestamp { get; set; }
        public string Request_ID { get; set; }
        public string Job_Order_No_ { get; set; }
        public int Business_Unit { get; set; }
        public string Job_Contract_No_ { get; set; }
        public string Bill_to_Customer_No_ { get; set; }
        public string Pick_up_Description { get; set; }
        public string Origin_Description { get; set; }
        public string Destination_Description { get; set; }
        public string Export_Entry_Declaration { get; set; }
        public string Packing_List_No_ { get; set; }
        public string Commercial_Invoice_No_ { get; set; }
        public string Customer_Reference_No_ { get; set; }
        public string Shipping_Agent { get; set; }
        public string Bil_of_Lading_No_ { get; set; }
        public string Ordinary_Transire_No_ { get; set; }
        public string Airway_Bill_No_ { get; set; }
        public string Car_Manifest_No_ { get; set; }
        public string Import_Entry_Declaration { get; set; }
        public string Pilotage_No_ { get; set; }
        public string Port_Clearance_No_ { get; set; }
        public System.DateTime ATA_Date { get; set; }
        public System.DateTime ETA_Date { get; set; }
        public System.DateTime Clearance_Date { get; set; }
        public System.DateTime Plan_Clearing_Date { get; set; }
        public string Package { get; set; }
        public string Delivery_Place { get; set; }
        public decimal Item_List_No_ { get; set; }
        public string Receipt_DO_From { get; set; }
        public string Information_Of_Conveyance_No_ { get; set; }
        public System.DateTime Temporary_Date { get; set; }
        public System.DateTime Return_Temporary_Date { get; set; }
        public string Consignee_No_ { get; set; }
        public string Consignee_Name { get; set; }
        public string Well_Name { get; set; }
        public string Well_Number { get; set; }
        public System.DateTime Date_of_Disposal { get; set; }
        public string Type_of_Waste { get; set; }
        public int Payment_Condition { get; set; }
        public string Customer_Operation { get; set; }
        public string Manifest_No_ { get; set; }
        public System.DateTime Request_Date_Time { get; set; }
        public System.DateTime Due_Date_Time { get; set; }
        public System.DateTime Extend_Start_Date { get; set; }
        public System.DateTime Extend_End_Date { get; set; }
        public string Formality_Mode { get; set; }
        public string Port { get; set; }
        public string Cargo_Type { get; set; }
        public string Declaration_Type { get; set; }
        public string Vessel_Name { get; set; }
        public string Formality_Sub_Type { get; set; }
        public System.DateTime Planning_Start_Date { get; set; }
        public System.DateTime Planning_End_Date { get; set; }
        public System.DateTime Appointment_Date { get; set; }
        public System.DateTime Appointment_Time { get; set; }
        public System.DateTime Pickup_Date { get; set; }
        public string Remark { get; set; }
        public int Page_Type { get; set; }
        public string Work_Order_No_ { get; set; }
        public string Job_Process_No_ { get; set; }
        public string Contact_Name { get; set; }
        public decimal Amount { get; set; }
        public decimal Actual_Amount { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public byte Confirm_ { get; set; }
        public System.DateTime Timestamp_ { get; set; }
        public string Truck_No { get; set; }
        public string Province { get; set; }
        public string Ship_Point { get; set; }
        public string Cust_Name { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public int Coil { get; set; }
        public decimal Wcoil { get; set; }
        public int Reel { get; set; }
        public decimal Wreel { get; set; }
        public decimal Wsum { get; set; }
        public string Type { get; set; }
        public string Load { get; set; }
        public int Type_Status { get; set; }
        public string Customer_Ref { get; set; }
        public string Shipping_Name { get; set; }
        public string Packing_List_No { get; set; }
        public string Remark1 { get; set; }
        public string PO_NO { get; set; }
        public string UserCreate { get; set; }
        public System.DateTime Delivery_Date { get; set; }
        public decimal TotalW { get; set; }
        public string Supplier_Name { get; set; }
        public string MAWB_No { get; set; }
        public string HAWB_No { get; set; }
        public string Booking_No { get; set; }
        public string OriginLInputTel { get; set; }
        public string DestinationTel { get; set; }
        public string Loading_Location { get; set; }
        public string Contact_Loading_Location_Tel { get; set; }
        public string Contact_Person { get; set; }
    }
}
