//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHENAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Logistics_CO___LTD__Resource_Planning
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public string Resource_Planning_Category { get; set; }
        public string Employee_No_ { get; set; }
        public string License_Plate_No_ { get; set; }
        public decimal Mileage { get; set; }
        public string Last_Work_Order_Update { get; set; }
        public decimal Initial_Mileage { get; set; }
        public System.DateTime Initial_Date { get; set; }
        public string Vehicle_Brand { get; set; }
        public string Vehicle_Model { get; set; }
        public int Container_Type { get; set; }
        public byte Allow_to_have_Trailer { get; set; }
        public string Serial_Number { get; set; }
        public string Internal_Equipment_No_ { get; set; }
        public int Warehouse_Type { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public decimal Total_Area { get; set; }
        public decimal Available_Area { get; set; }
        public decimal Working_Hour { get; set; }
        public decimal Initial_Hour { get; set; }
        public string Position { get; set; }
        public string Title { get; set; }
        public int Position_ID { get; set; }
        public string Position_Name { get; set; }
        public string Tax_ID { get; set; }
        public string Shortcut_Dimension_1_Code { get; set; }
        public string Shortcut_Dimension_2_Code { get; set; }
        public string Transport_Province { get; set; }
        public string Transport_Company { get; set; }
        public string Transport_Location { get; set; }
        public string Color { get; set; }
        public string Classis_No_ { get; set; }
        public string Engne_No_ { get; set; }
        public decimal CC { get; set; }
        public string Fuel { get; set; }
        public decimal Weight { get; set; }
        public string Mobile_ID { get; set; }
        public string Active_Mobile_ID { get; set; }
        public int Unit_Id { get; set; }
        public string Unit_Name { get; set; }
        public string Job_Grade { get; set; }
        public string Job_Family { get; set; }
        public int Personnel_Area_Id { get; set; }
        public string Personnel_Area_Name { get; set; }
        public int Contact_Id { get; set; }
        public int Company { get; set; }
        public int Last_Mileage { get; set; }
        public int Status { get; set; }
        public System.Guid Picture { get; set; }
        public int Truck_Status { get; set; }
        public string FA_No_ { get; set; }
        public string UID { get; set; }
        public string Ref__MHE_ID { get; set; }
        public decimal Fuel_Tank_Capacity { get; set; }
        public decimal Useful_Life { get; set; }
        public string MHE_Name { get; set; }
    }
}
