//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHENAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_MHE_TR_Entries
    {
        public int ID { get; set; }
        public string Customer { get; set; }
        public string Contract_No { get; set; }
        public string BU { get; set; }
        public string Base { get; set; }
        public string Req_No { get; set; }
        public string Confirm { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public string Truck_No { get; set; }
        public string Province { get; set; }
        public string Origin { get; set; }
        public string Actual_ { get; set; }
        public string Ship_Point { get; set; }
        public string Cust_Name { get; set; }
        public string Ship_To { get; set; }
        public string Contact { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string Coil { get; set; }
        public string Wcoil { get; set; }
        public string Reel { get; set; }
        public string Wreel { get; set; }
        public string Wsum { get; set; }
        public string Type { get; set; }
        public string Load { get; set; }
        public Nullable<int> Type_Status { get; set; }
        public string Customer_Ref { get; set; }
        public string Package { get; set; }
        public string Cargo_Type { get; set; }
        public string Formality_Sup { get; set; }
        public string Formality_Mode { get; set; }
        public string Port { get; set; }
        public Nullable<System.DateTime> ETA_Date { get; set; }
        public Nullable<System.DateTime> ATA_Date { get; set; }
        public string Shipping_Agent { get; set; }
        public string Shipping_Name { get; set; }
        public Nullable<System.DateTime> Plan_Clearing_Date { get; set; }
        public string Airway_Bill_No { get; set; }
        public string Delivery_Place { get; set; }
        public Nullable<System.DateTime> Clearanc_Date { get; set; }
        public string Export_Entry_Declaration { get; set; }
        public string Packing_List_No { get; set; }
        public string Commercial_Invoice { get; set; }
        public Nullable<int> QTY { get; set; }
        public string Unit { get; set; }
        public string Detail { get; set; }
        public string Remark { get; set; }
        public string WO_No { get; set; }
        public string PO_NO { get; set; }
        public string UserCreate { get; set; }
        public string CusRefNo { get; set; }
        public string Jobprocess { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public Nullable<double> TotalW { get; set; }
        public Nullable<System.DateTime> Clearance_Date { get; set; }
        public string Supplier_Name { get; set; }
        public string MAWB_No { get; set; }
        public string Bil_of_Lading_No { get; set; }
        public string HAWB_No { get; set; }
        public string Booking_No { get; set; }
        public string OriginLInputTel { get; set; }
        public string DestinationTel { get; set; }
        public string Loading_Location { get; set; }
        public string Contact_Loading_Location_Tel { get; set; }
        public string Import_Entry_Declaration { get; set; }
        public string CheckTypeBU { get; set; }
        public Nullable<System.DateTime> DateNow { get; set; }
        public Nullable<System.TimeSpan> Start_Time { get; set; }
        public Nullable<System.TimeSpan> End_Time { get; set; }
        public string Company { get; set; }
        public string Model { get; set; }
        public string Contract_Type { get; set; }
        public string Vehicle_SN { get; set; }
        public string From_Location { get; set; }
        public string To_Location { get; set; }
        public string Requester { get; set; }
        public string Contact_Number { get; set; }
        public string Description { get; set; }
        public string Driver { get; set; }
        public string Signaler { get; set; }
        public string Driver_2 { get; set; }
        public string Signaler_2 { get; set; }
        public string Approval_Status { get; set; }
        public string Approver_Remark { get; set; }
        public string Note { get; set; }
        public string Shift { get; set; }
        public string J_Type { get; set; }
        public string Driver_Sub { get; set; }
    }
}
