//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHENAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_MHE_TimeSheet
    {
        public int ID { get; set; }
        public Nullable<int> TS_No { get; set; }
        public Nullable<System.DateTime> TS_Date_Request { get; set; }
        public string TS_Customer { get; set; }
        public string TS_Vehicle_Type { get; set; }
        public string TS_Vehicle_SN { get; set; }
    }
}
